import { theme } from './theme';

export const styles = {
  body: {
    backgroundColor: theme.colors.bodyBg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    padding: theme.spacing.md,
    fontFamily: 'Inter, sans-serif',
  },
  phoneFrame: {
    width: '100%',
    maxWidth: 390,
    height: 844,
    backgroundColor: theme.colors.white,
    border: `8px solid ${theme.colors.phoneFrame}`,
    borderRadius: 40,
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative'
  },
  appContainer: { flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' },
  screenScroll: { flex: 1, backgroundColor: theme.colors.background, overflowY: 'auto' as const },
  screenContainer: { padding: `0 ${theme.spacing.lg}px`, flexGrow: 1 },
  centeredScreen: { flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center' },
  // Typography
  h1: { fontSize: 24, fontWeight: theme.font.bold, color: theme.colors.textPrimary },
  h2: { fontSize: 20, fontWeight: theme.font.bold, color: theme.colors.textPrimary },
  h3: { fontSize: 18, fontWeight: theme.font.bold, color: theme.colors.textPrimary },
  // Header
  header: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: theme.spacing.lg },
  avatar: { width: 40, height: 40, borderRadius: 20, marginRight: theme.spacing.md },
  notificationDot: { position: 'absolute', top: 0, right: 0, width: 10, height: 10, backgroundColor: theme.colors.red, borderRadius: 5, border: `2px solid ${theme.colors.background}` },
  // Search Bar
  searchInput: { width: '100%', boxSizing: 'border-box' as const, paddingLeft: 48, paddingRight: 16, paddingBlock: 16, backgroundColor: theme.colors.card, border: `1px solid ${theme.colors.border}`, borderRadius: 12, fontSize: 16 },
  searchIcon: { position: 'absolute', left: 16, top: '50%', transform: 'translateY(-50%)', fontSize: 20, color: theme.colors.textTertiary, zIndex: 1 },
  // Home Screen Tabs
  hotDealTabs: { display: 'flex', flexDirection: 'row', gap: theme.spacing.lg, borderBottom: `1px solid ${theme.colors.border}`, margin: `${theme.spacing.md}px 0` },
  hotDealTab: { 
    paddingBottom: theme.spacing.sm, 
    color: theme.colors.textSecondary, 
    fontSize: 16, 
    backgroundColor: 'transparent', 
    border: 'none', 
    cursor: 'pointer',
    borderBottom: '3px solid transparent',
  },
  hotDealTabActive: { 
    fontWeight: theme.font.bold, 
    color: theme.colors.amber600, 
    borderBottom: `3px solid ${theme.colors.amber400}`,
  },
  // Navigation Bar
  navBar: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 96,
    paddingBottom: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderTop: '1px solid rgba(230, 230, 230, 0.8)',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backdropFilter: 'blur(10px)',
  },
  navBtn: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: theme.spacing.xs, flex: 1, backgroundColor: 'transparent', border: 'none', cursor: 'pointer' },
  navIcon: { width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'transform 0.2s' },
  navIconActive: { transform: 'scale(1.15) translateY(-3px)' },
  navLabel: { fontSize: 12, color: theme.colors.textSecondary },
  navLabelActive: { fontWeight: theme.font.bold, color: theme.colors.textPrimary },
  scanButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -40,
    border: 'none',
    cursor: 'pointer',
    boxShadow: `0 4px 15px ${theme.colors.amber400}80`,
  },
} as const;;